### ISSUE TITLE
Keybind for taser is not working

### ISSUE THREAD

**Issue by Kr0llx** [jessewebb/csgo-buynds#14]
Your current configuration prints " bind "$" "buy **Taser**;" " for binding Taser to a key, but this doesn't work any more. I figured out that it hast to be changed to " bind "$" "buy **taser 34**;" ". This shouldn't be a big problem. (tested today)

And thanks for this awesom projekt.

**Comment by jessewebb** [comment]
This is fixed now. Thanks for reporting the issue!
