### ISSUE TITLE
Quotation marks are placed incorrectly in the end result.

### ISSUE THREAD

**Issue by Yodzeity** [jessewebb/csgo-buynds#24]
Current state:

bind "kp_leftarrow" "buy deagle;"
bind "kp_5" "buy tec9; buy fiveseven;"

Should be:

bind "kp_leftarrow" "buy deagle";
bind "kp_5" "buy tec9; buy fiveseven";

**Comment by jessewebb** [comment]
You don't want semi-colons at the end of the line in your autoexec.cfg. You would only want semi-colons at the end if you are trying to paste these binds into your console, which I don't recommend. 

See the new help page for more info: http://csgobuynds.com/help.html
