### ISSUE TITLE
Copy to Clipboard button doesnt work.

### ISSUE THREAD

**Issue by mxxfun** [jessewebb/csgo-buynds#25]
When you click the "copy to clipboard" button nothing happens.

![image](https://user-images.githubusercontent.com/17051822/36800119-f8d60b8e-1cae-11e8-81c2-c2613e47ac81.png)

Windows 10/Google chrome

**Comment by jessewebb** [comment]
The current "Copy to Clipboard" button uses Flash. Flash _should_ work in Chrome, but it is possible you have it disabled or something else is preventing the Flash plugin from working properly. Either way, Flash is a less-than-ideal solution to this problem.

In the current development branch, I have already updated the "Copy to Clipboard" button to use a pure JavaScript solution, so it doesn't require Flash to work properly. This should work much better for most users.
Commit: 793dd5b9cdfb90ef83415692db8ec2c2692f03a0

This will be part of the 1.0 release which should be coming out soon.

**Comment by mxxfun** [comment]
Okay sounds good!
