### ISSUE TITLE
Flashbang double buy logic issue

### ISSUE THREAD

**Issue by B1zmark** [jessewebb/csgo-buynds#3]
Hi,

The way the binds are generated, it's possible to double-buy flash bangs if you already hold one from the round before.

I'd recommend always having flash bangs as the final purchase (after all other grenades) to prevent accidentally having 2 flash bangs and blocking the purchase of other grenades.

Thanks,
Biz

**Comment by jessewebb** [comment]
An undocumented "feature" of my buy binds generator is that it will order the item purchases of the buy binds in the same order you have clicked on the checkboxes on the website. This is true for the "Grenades" section as well as the "Gear" section. The purchase order does not take both sections into consideration; the generated binds will always order "Gear" before "Grenades".

For example, if you click on the single "Flashbang" checkbox, and then the "Decoy" checkbox, and then the "Flashbang x2" checkbox, your generated bind will look like this:

`buy flashbang; buy decoy; buy flashbang;`

Then, if you were to click on the "Molotov / Incendiary" checkbox, your generated bind would look like this:

`buy flashbang; buy decoy; buy flashbang; buy molotov; buy incgrenade;`

Then, if you were to click on the "Defuse Kit" checkbox and then the "Kevlar Vest" checkbox, your generated bind would look like this:

`buy defuser; buy vest; buy flashbang; buy decoy; buy flashbang; buy molotov; buy incgrenade;`

Notice how all the "Gear" appears first in the list followed by all the "Grenades" but both sub-lists are in the order you clicked on the checkboxes.

This means that the website lets you control the order items are purchased in. There is no logic I need to fix, you just need to re-generate your binds while clicking on items in the order you desire them to be purchased.
