### ISSUE TITLE
How about add arrow key?

### ISSUE THREAD

**Issue by kurodz** [jessewebb/csgo-buynds#4]
Arrow key is good to use too , how about that ?

**Comment by jessewebb** [comment]
In the upcoming version `0.8` I have added the arrows keys and most of the other keys found on a standard EN-US keyboard to the list of bindable keys. These will all be available from the Single-Key Generator (SKG).

I do also want to add more key options to the Multi-Key Generator but it is a little trickier to do so. Don't expect it in version `0.8` but i will try to work this into `0.9`.
