### ISSUE TITLE
Flash bang double buy

### ISSUE THREAD

**Issue by sebbi08** [jessewebb/csgo-buynds#8]
I would set the Flashbang always as last command because otherwise it will be baught a second time if oneis already in inventory

**Comment by jessewebb** [comment]
The user is able to choose which order grenades are bought by clicking on the check-boxes in the same order they wish the item to be used in the generated bind.
- If the user first clicks on "Flashbang" and then "Decoy" and then the "x 2" for a second flashbang, the generated bind will be: `buy flashbang; buy decoy; buy flashbang;`
- If the user first clicks on "Smoke" and then "Flashbang" and then the "x 2" ad then "Decoy", the generated bind will be: `buy smokegrenade; buy flashbang; buy flashbang; buy decoy;`

This is true for items in the Equipment menu too.

Closing this request as "Won't Fix".
